name: PHPStan
on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'config/**'
      - 'phpstan.neon.dist'
      - 'phpstan-baseline.neon'
      - '.github/workflows/phpstan.yml'
  pull_request:
permissions:
  contents: read
jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: 'false'
          show-progress: 'false'
          fetch-depth: '1'
      - name: Check for relevant changes
        id: changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            src:
              - '**.php'
              - 'composer.json'
              - 'composer.lock'
              - 'config/**'
              - 'phpstan.neon.dist'
              - 'phpstan-baseline.neon'
              - '.github/workflows/phpstan.yml'
      - name: Setup PHP
        if: steps.changes.outputs.src == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install composer dependencies
        if: steps.changes.outputs.src == 'true'
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHPStan
        if: steps.changes.outputs.src == 'true'
        run: ./vendor/bin/phpstan analyse --error-format=github --memory-limit=2G
