name: "Check PHP Code Style"

on:
  push:
    branches: [master]
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'pint.json'
      - '.github/workflows/pint-check.yml'
  pull_request:

permissions:
  contents: read

jobs:
  pint:
    name: Pint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          show-progress: 'false'
          fetch-depth: '1'
      - name: Check for relevant changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - '**.php'
              - 'composer.json'
              - 'composer.lock'
              - 'pint.json'
              - '.github/workflows/pint-check.yml'
      - name: Setup PHP
        if: steps.changes.outputs.src == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install composer dependencies
        if: steps.changes.outputs.src == 'true'
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Check PHP code style
        if: steps.changes.outputs.src == 'true'
        run: composer test:lint
